/// <reference path="../typings/tsd.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../scenes/RightZone.ts" />
/// <reference path="../scenes/LeftZone.ts" />
/// <reference path="../scenes/intro.ts" />
/// <reference path="../scenes/Start.ts" />
/// <reference path="../scenes/northzone.ts" />
/// <reference path="../scenes/NorthExit2.ts" />
/// <reference path="../scenes/NorthExit1.ts" />
/// <reference path="../scenes/southzone.ts" />
/// <reference path="../scenes/SouthExit1.ts" />
/// <reference path="../scenes/SouthExit2.ts" />
/// <reference path="../scenes/EastExit1.ts" />
/// <reference path="../scenes/EastExit2.ts" />
/// <reference path="../scenes/East.ts" />
/// <reference path="../scenes/West.ts" />
/// <reference path="../scenes/WestExit1.ts" />
/// <reference path="../scenes/WestExit2.ts" /> 
//# sourceMappingURL=_reference.js.map